/*
# CRM Multi-tenant: Leads, Interactions, Follow-ups

1. New Tables

### leads
Central CRM entity tracking each prospect per dealer.
- id (uuid, pk)
- dealer_id (uuid, fk dealers, cascade)
- client_id (uuid, fk clients, set null) — links to existing customers table
- vehicle_id (uuid, fk vehicles, set null) — vehicle of interest
- name, phone, email — denormalized for quick capture (auto-create client when needed)
- source (text) — where the lead came from: whatsapp, instagram, facebook, olx, webmotors, mercado_livre, google, qr_code, site, referral, walk_in, other
- source_detail (text) — campaign name, ad ID, UTM info, etc.
- status (text) — pipeline stage: new, contacted, qualified, proposal, negotiation, won, lost
- lead_score (int 0-100) — AI/manual scoring of lead quality
- budget (numeric) — customer's stated budget
- down_payment (numeric) — stated down payment
- max_installment (numeric) — max monthly payment they can afford
- notes (text)
- last_interaction_at (timestamptz) — updated on each interaction
- assigned_to (text) — seller name (no separate sellers table yet)
- created_at, updated_at

### lead_interactions
History of every touchpoint with a lead.
- id (uuid, pk)
- lead_id (uuid, fk leads, cascade)
- dealer_id (uuid, fk dealers, cascade) — for direct ownership queries
- type (text) — call, whatsapp, email, message, visit, test_drive, proposal_sent, financing_sent, note
- description (text)
- vehicle_id (uuid, fk vehicles, set null) — vehicle involved in this interaction
- created_at

### lead_follow_ups
Scheduled follow-up tasks per lead.
- id (uuid, pk)
- lead_id (uuid, fk leads, cascade)
- dealer_id (uuid, fk dealers, cascade)
- scheduled_at (timestamptz) — when the follow-up is due
- message (text) — suggested or custom message
- type (text) — call, whatsapp, email, visit, reminder
- status (text) — pending, done, skipped
- ai_suggested (boolean) — true if generated by AI suggestion
- completed_at (timestamptz)
- created_at

2. Security
- RLS enabled on all 3 tables
- Owner-scoped CRUD via dealers ownership check (same pattern as existing tables)
- 4 policies each (select/insert/update/delete) TO authenticated

3. Indexes
- leads: dealer_id, status, vehicle_id, client_id
- lead_interactions: lead_id, dealer_id
- lead_follow_ups: lead_id, dealer_id, status, scheduled_at
*/

-- === LEADS ===
CREATE TABLE IF NOT EXISTS leads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  dealer_id uuid NOT NULL REFERENCES dealers(id) ON DELETE CASCADE,
  client_id uuid REFERENCES clients(id) ON DELETE SET NULL,
  vehicle_id uuid REFERENCES vehicles(id) ON DELETE SET NULL,
  name text NOT NULL,
  phone text,
  email text,
  source text NOT NULL DEFAULT 'other' CHECK (source IN ('whatsapp','instagram','facebook','olx','webmotors','mercado_livre','google','qr_code','site','referral','walk_in','other')),
  source_detail text,
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new','contacted','qualified','proposal','negotiation','won','lost')),
  lead_score integer NOT NULL DEFAULT 50 CHECK (lead_score >= 0 AND lead_score <= 100),
  budget numeric(12,2),
  down_payment numeric(12,2),
  max_installment numeric(12,2),
  notes text,
  last_interaction_at timestamptz,
  assigned_to text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_leads_dealer ON leads(dealer_id);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_vehicle ON leads(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_leads_client ON leads(client_id);

ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_leads" ON leads;
CREATE POLICY "select_own_leads" ON leads FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = leads.dealer_id AND dealers.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "insert_own_leads" ON leads;
CREATE POLICY "insert_own_leads" ON leads FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = leads.dealer_id AND dealers.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "update_own_leads" ON leads;
CREATE POLICY "update_own_leads" ON leads FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = leads.dealer_id AND dealers.user_id = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = leads.dealer_id AND dealers.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "delete_own_leads" ON leads;
CREATE POLICY "delete_own_leads" ON leads FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = leads.dealer_id AND dealers.user_id = auth.uid())
  );

-- === LEAD INTERACTIONS ===
CREATE TABLE IF NOT EXISTS lead_interactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  dealer_id uuid NOT NULL REFERENCES dealers(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('call','whatsapp','email','message','visit','test_drive','proposal_sent','financing_sent','note')),
  description text,
  vehicle_id uuid REFERENCES vehicles(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_interactions_lead ON lead_interactions(lead_id);
CREATE INDEX IF NOT EXISTS idx_lead_interactions_dealer ON lead_interactions(dealer_id);

ALTER TABLE lead_interactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_interactions" ON lead_interactions;
CREATE POLICY "select_own_interactions" ON lead_interactions FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = lead_interactions.dealer_id AND dealers.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "insert_own_interactions" ON lead_interactions;
CREATE POLICY "insert_own_interactions" ON lead_interactions FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = lead_interactions.dealer_id AND dealers.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "update_own_interactions" ON lead_interactions;
CREATE POLICY "update_own_interactions" ON lead_interactions FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = lead_interactions.dealer_id AND dealers.user_id = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = lead_interactions.dealer_id AND dealers.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "delete_own_interactions" ON lead_interactions;
CREATE POLICY "delete_own_interactions" ON lead_interactions FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = lead_interactions.dealer_id AND dealers.user_id = auth.uid())
  );

-- === LEAD FOLLOW UPS ===
CREATE TABLE IF NOT EXISTS lead_follow_ups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  dealer_id uuid NOT NULL REFERENCES dealers(id) ON DELETE CASCADE,
  scheduled_at timestamptz NOT NULL,
  message text,
  type text NOT NULL DEFAULT 'whatsapp' CHECK (type IN ('call','whatsapp','email','visit','reminder')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','done','skipped')),
  ai_suggested boolean NOT NULL DEFAULT false,
  completed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_follow_ups_lead ON lead_follow_ups(lead_id);
CREATE INDEX IF NOT EXISTS idx_lead_follow_ups_dealer ON lead_follow_ups(dealer_id);
CREATE INDEX IF NOT EXISTS idx_lead_follow_ups_status ON lead_follow_ups(status);
CREATE INDEX IF NOT EXISTS idx_lead_follow_ups_scheduled ON lead_follow_ups(scheduled_at);

ALTER TABLE lead_follow_ups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_follow_ups" ON lead_follow_ups;
CREATE POLICY "select_own_follow_ups" ON lead_follow_ups FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = lead_follow_ups.dealer_id AND dealers.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "insert_own_follow_ups" ON lead_follow_ups;
CREATE POLICY "insert_own_follow_ups" ON lead_follow_ups FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = lead_follow_ups.dealer_id AND dealers.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "update_own_follow_ups" ON lead_follow_ups;
CREATE POLICY "update_own_follow_ups" ON lead_follow_ups FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = lead_follow_ups.dealer_id AND dealers.user_id = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = lead_follow_ups.dealer_id AND dealers.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "delete_own_follow_ups" ON lead_follow_ups;
CREATE POLICY "delete_own_follow_ups" ON lead_follow_ups FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM dealers WHERE dealers.id = lead_follow_ups.dealer_id AND dealers.user_id = auth.uid())
  );